// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmZWaaC-q3_GpWpXtZQdkISadaM4VG-a4',
    appId: '1:739597429843:web:de1caec21aff5e5a512aa6',
    messagingSenderId: '739597429843',
    projectId: 'richupapp',
    authDomain: 'richupapp.firebaseapp.com',
    databaseURL: 'https://richupapp-default-rtdb.firebaseio.com',
    storageBucket: 'richupapp.firebasestorage.app',
    measurementId: 'G-G12FD119JQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHGJgkSGATFSNr8oX201CxegmBlIP5VKc',
    appId: '1:739597429843:android:01f9e35a5da754d9512aa6',
    messagingSenderId: '739597429843',
    projectId: 'richupapp',
    databaseURL: 'https://richupapp-default-rtdb.firebaseio.com',
    storageBucket: 'richupapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_0-lz3VLhcsQYzYQfJin_S-H71OyRJu0',
    appId: '1:739597429843:ios:3a35fab7f86b1c0e512aa6',
    messagingSenderId: '739597429843',
    projectId: 'richupapp',
    databaseURL: 'https://richupapp-default-rtdb.firebaseio.com',
    storageBucket: 'richupapp.firebasestorage.app',
    androidClientId: '739597429843-47os5n2e35a5i7ormckolceebp5giahl.apps.googleusercontent.com',
    iosClientId: '739597429843-28hg99u6gq4adfrd9i6qf8nag249o85p.apps.googleusercontent.com',
    iosBundleId: 'com.simplewaytechnology.chashview',
  );

}